image: golang:latest

before_script:
  - export GOPROXY=https://goproxy.cn
  - go get golang.org/x/tools/cmd/goimports
#  - apt-get update && apt-get install -y curl 

stages:
  - test
  - build
  - integration-test
#  - deploy

format-job:
  stage: test
  tags:
    - golang
  script:
    - goimports -d .
    - test -z "$(goimports -d .)"
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -short -race $(go list ./... | grep -v /vendor/)

build-job:
  stage: build
  tags:
    - golang
  script:
    - echo "Compiling the code..."
    - cd cmd
    - go build -race -ldflags "-extldflags '-static'" -o search_proxy main.go
    - echo "Compile complete."
  artifacts:
    paths:
      - cmd
      - configs

#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
