[server]
ip = ""
port = 7070

[log]
level = "info"      #可能的值：debug, info, warn, error
file_path = "../logs/proxy.log"
max_size = 128       #在进行切割之前，日志文件的最大大小（以MB为单位）
max_backups = 100    #保留旧文件的最大个数
max_age = 60         #保留旧文件的最大天数
compress = true      #是否压缩/归档旧文件

[router]
mode = "poll"        #可能的值：poll, rand, hash

[group]
timeout = 80

[group0]
master = "127.0.0.1:7788"
slave = ["127.0.0.1:7788", "127.0.0.1:7788"]

[group1]
master = "127.0.0.1:7799"
slave = ["127.0.0.1:7799", "127.0.0.1:7799"]
